## Pandas
    * behaves like MS Excel
    * used to load data from outside into our script
    * read_csv(file_path), read_json(), read_excel(), read_html() etc

In [16]:
import pandas as pd

In [69]:
iris = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", header = None)
iris.columns = ['sl', 'sw', 'pl', 'pw', 'flower_type']
iris

      sl   sw   pl   pw     flower_type
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
5    5.4  3.9  1.7  0.4     Iris-setosa
6    4.6  3.4  1.4  0.3     Iris-setosa
7    5.0  3.4  1.5  0.2     Iris-setosa
8    4.4  2.9  1.4  0.2     Iris-setosa
9    4.9  3.1  1.5  0.1     Iris-setosa
10   5.4  3.7  1.5  0.2     Iris-setosa
11   4.8  3.4  1.6  0.2     Iris-setosa
12   4.8  3.0  1.4  0.1     Iris-setosa
13   4.3  3.0  1.1  0.1     Iris-setosa
14   5.8  4.0  1.2  0.2     Iris-setosa
15   5.7  4.4  1.5  0.4     Iris-setosa
16   5.4  3.9  1.3  0.4     Iris-setosa
17   5.1  3.5  1.4  0.3     Iris-setosa
18   5.7  3.8  1.7  0.3     Iris-setosa
19   5.1  3.8  1.5  0.3     Iris-setosa
20   5.4  3.4  1.7  0.2     Iris-setosa
21   5.1  3.7  1.5  0.4     Iris-setosa
22   4.6  3.6  1.0  0.2     Iris-setosa
23   5.1  3.3  1.7  0.5     Iris-setosa
24   4.8  3.4  1.9  0.2     Iris-setosa
25   5.0  3.0  1.6  0.2     Iris-setosa
26   5.0  3.4  1.6  0.4     Iris-setosa
27   5.2  3.5  1.5  0.2     Iris-setosa
28   5.2  3.4  1.4  0.2     Iris-setosa
29   4.7  3.2  1.6  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
120  6.9  3.2  5.7  2.3  Iris-virginica
121  5.6  2.8  4.9  2.0  Iris-virginica
122  7.7  2.8  6.7  2.0  Iris-virginica
123  6.3  2.7  4.9  1.8  Iris-virginica
124  6.7  3.3  5.7  2.1  Iris-virginica
125  7.2  3.2  6.0  1.8  Iris-virginica
126  6.2  2.8  4.8  1.8  Iris-virginica
127  6.1  3.0  4.9  1.8  Iris-virginica
128  6.4  2.8  5.6  2.1  Iris-virginica
129  7.2  3.0  5.8  1.6  Iris-virginica
130  7.4  2.8  6.1  1.9  Iris-virginica
131  7.9  3.8  6.4  2.0  Iris-virginica
132  6.4  2.8  5.6  2.2  Iris-virginica
133  6.3  2.8  5.1  1.5  Iris-virginica
134  6.1  2.6  5.6  1.4  Iris-virginica
135  7.7  3.0  6.1  2.3  Iris-virginica
136  6.3  3.4  5.6  2.4  Iris-virginica
137  6.4  3.1  5.5  1.8  Iris-virginica
138  6.0  3.0  4.8  1.8  Iris-virginica
139  6.9  3.1  5.4  2.1  Iris-virginica
140  6.7  3.1  5.6  2.4  Iris-virginica
141  6.9  3.1  5.1  2.3  Iris-virginica
142  5.8  2.7  5.1  1.9  Iris-virginica
143  6.8  3.2  5.9  2.3  Iris-virginica
144  6.7  3.3  5.7  2.5  Iris-virginica
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [18]:
# df = iris.copy() is fine too
import copy
df = copy.deepcopy(iris)

# head(n=5) member function return n number of records
# default is 5
df.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [19]:
print(df.shape)

(150, 5)

In [20]:
print(df.dtypes)

0    float64
1    float64
2    float64
3    float64
4     object
dtype: object

In [21]:
df.columns

Int64Index([0, 1, 2, 3, 4], dtype='int64')

In [22]:
df.columns = ['sl', 'sw', 'pl', 'pw', 'flower_type']
df.head()

    sl   sw   pl   pw  flower_type
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [23]:
df.describe()

               sl          sw          pl          pw
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667
std      0.828066    0.433594    1.764420    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [24]:
# df.column_name
print(df.sl.head())
print(df["sl"].head())

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sl, dtype: float64
0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sl, dtype: float64

In [25]:
df.isnull()

        sl     sw     pl     pw  flower_type
0    False  False  False  False        False
1    False  False  False  False        False
2    False  False  False  False        False
3    False  False  False  False        False
4    False  False  False  False        False
5    False  False  False  False        False
6    False  False  False  False        False
7    False  False  False  False        False
8    False  False  False  False        False
9    False  False  False  False        False
10   False  False  False  False        False
11   False  False  False  False        False
12   False  False  False  False        False
13   False  False  False  False        False
14   False  False  False  False        False
15   False  False  False  False        False
16   False  False  False  False        False
17   False  False  False  False        False
18   False  False  False  False        False
19   False  False  False  False        False
20   False  False  False  False        False
21   False  False  False  False        False
22   False  False  False  False        False
23   False  False  False  False        False
24   False  False  False  False        False
25   False  False  False  False        False
26   False  False  False  False        False
27   False  False  False  False        False
28   False  False  False  False        False
29   False  False  False  False        False
..     ...    ...    ...    ...          ...
120  False  False  False  False        False
121  False  False  False  False        False
122  False  False  False  False        False
123  False  False  False  False        False
124  False  False  False  False        False
125  False  False  False  False        False
126  False  False  False  False        False
127  False  False  False  False        False
128  False  False  False  False        False
129  False  False  False  False        False
130  False  False  False  False        False
131  False  False  False  False        False
132  False  False  False  False        False
133  False  False  False  False        False
134  False  False  False  False        False
135  False  False  False  False        False
136  False  False  False  False        False
137  False  False  False  False        False
138  False  False  False  False        False
139  False  False  False  False        False
140  False  False  False  False        False
141  False  False  False  False        False
142  False  False  False  False        False
143  False  False  False  False        False
144  False  False  False  False        False
145  False  False  False  False        False
146  False  False  False  False        False
147  False  False  False  False        False
148  False  False  False  False        False
149  False  False  False  False        False

[150 rows x 5 columns]

In [26]:
# find counts of null values in df
df.isnull().sum()

sl             0
sw             0
pl             0
pw             0
flower_type    0
dtype: int64

In [27]:
# for findind a sub dataframe
# just like submatrix using slicing 
df.iloc[1:4, 2:4]

    pl   pw
1  1.4  0.2
2  1.3  0.2
3  1.5  0.2

In [28]:
# manipulating dataframes

#drop removes the row whose index is passed
#and returns the altered dataframe

# to do it inplace pass inplace = True

"""
first argument passed is the 
actual index of the row to delete
every row has an index
so you cannot delete the 0th row more than once
"""

df = iris.copy()
print(df.head())
df2 = df.drop(2)
print(df2.head())
print(df.head())

#change back to initial df
df2 = df
df2.drop(3, inplace = True)
print(df2.head())

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa
     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa
5  5.4  3.9  1.7  0.4  Iris-setosa
     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa
     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa
5  5.4  3.9  1.7  0.4  Iris-setosa

In [29]:
# print row numbers/indices
print(df.index)


# df.index is list of indices of rows
# (that is list of row names)
# so to remove ith row
# pass df.index[i] as index for drop function


# eg to remove 0th row
df.drop(df.index[0])

Int64Index([  0,   1,   2,   4,   5,   6,   7,   8,   9,  10,
            ...
            140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
           dtype='int64', length=149)

       0    1    2    3               4
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
5    5.4  3.9  1.7  0.4     Iris-setosa
6    4.6  3.4  1.4  0.3     Iris-setosa
7    5.0  3.4  1.5  0.2     Iris-setosa
8    4.4  2.9  1.4  0.2     Iris-setosa
9    4.9  3.1  1.5  0.1     Iris-setosa
10   5.4  3.7  1.5  0.2     Iris-setosa
11   4.8  3.4  1.6  0.2     Iris-setosa
12   4.8  3.0  1.4  0.1     Iris-setosa
13   4.3  3.0  1.1  0.1     Iris-setosa
14   5.8  4.0  1.2  0.2     Iris-setosa
15   5.7  4.4  1.5  0.4     Iris-setosa
16   5.4  3.9  1.3  0.4     Iris-setosa
17   5.1  3.5  1.4  0.3     Iris-setosa
18   5.7  3.8  1.7  0.3     Iris-setosa
19   5.1  3.8  1.5  0.3     Iris-setosa
20   5.4  3.4  1.7  0.2     Iris-setosa
21   5.1  3.7  1.5  0.4     Iris-setosa
22   4.6  3.6  1.0  0.2     Iris-setosa
23   5.1  3.3  1.7  0.5     Iris-setosa
24   4.8  3.4  1.9  0.2     Iris-setosa
25   5.0  3.0  1.6  0.2     Iris-setosa
26   5.0  3.4  1.6  0.4     Iris-setosa
27   5.2  3.5  1.5  0.2     Iris-setosa
28   5.2  3.4  1.4  0.2     Iris-setosa
29   4.7  3.2  1.6  0.2     Iris-setosa
30   4.8  3.1  1.6  0.2     Iris-setosa
31   5.4  3.4  1.5  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
120  6.9  3.2  5.7  2.3  Iris-virginica
121  5.6  2.8  4.9  2.0  Iris-virginica
122  7.7  2.8  6.7  2.0  Iris-virginica
123  6.3  2.7  4.9  1.8  Iris-virginica
124  6.7  3.3  5.7  2.1  Iris-virginica
125  7.2  3.2  6.0  1.8  Iris-virginica
126  6.2  2.8  4.8  1.8  Iris-virginica
127  6.1  3.0  4.9  1.8  Iris-virginica
128  6.4  2.8  5.6  2.1  Iris-virginica
129  7.2  3.0  5.8  1.6  Iris-virginica
130  7.4  2.8  6.1  1.9  Iris-virginica
131  7.9  3.8  6.4  2.0  Iris-virginica
132  6.4  2.8  5.6  2.2  Iris-virginica
133  6.3  2.8  5.1  1.5  Iris-virginica
134  6.1  2.6  5.6  1.4  Iris-virginica
135  7.7  3.0  6.1  2.3  Iris-virginica
136  6.3  3.4  5.6  2.4  Iris-virginica
137  6.4  3.1  5.5  1.8  Iris-virginica
138  6.0  3.0  4.8  1.8  Iris-virginica
139  6.9  3.1  5.4  2.1  Iris-virginica
140  6.7  3.1  5.6  2.4  Iris-virginica
141  6.9  3.1  5.1  2.3  Iris-virginica
142  5.8  2.7  5.1  1.9  Iris-virginica
143  6.8  3.2  5.9  2.3  Iris-virginica
144  6.7  3.3  5.7  2.5  Iris-virginica
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[148 rows x 5 columns]

In [38]:
df[0] > 5

0       True
1      False
2      False
4      False
5       True
6      False
7      False
8      False
9      False
10      True
11     False
12     False
13     False
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22     False
23      True
24     False
25     False
26     False
27      True
28      True
29     False
30     False
       ...
120     True
121     True
122     True
123     True
124     True
125     True
126     True
127     True
128     True
129     True
130     True
131     True
132     True
133     True
134     True
135     True
136     True
137     True
138     True
139     True
140     True
141     True
142     True
143     True
144     True
145     True
146     True
147     True
148     True
149     True
Name: 0, Length: 149, dtype: bool

In [41]:
df.columns = ['sl', 'sw', 'pl', 'pw', "flower_type"]
df[df.flower_type == 'Iris-virginica'].describe()

             sl         sw         pl        pw
count  50.00000  50.000000  50.000000  50.00000
mean    6.58800   2.974000   5.552000   2.02600
std     0.63588   0.322497   0.551895   0.27465
min     4.90000   2.200000   4.500000   1.40000
25%     6.22500   2.800000   5.100000   1.80000
50%     6.50000   3.000000   5.550000   2.00000
75%     6.90000   3.175000   5.875000   2.30000
max     7.90000   3.800000   6.900000   2.50000

In [46]:
# iloc works by position
# loc works by row index name

print(df.head())
print(df.iloc[0])
print(df.loc[5])

# add a row to dataframe

df.loc[df.shape[0] + 2] = [1.5, 2.7, 3.2, 4.8, "Iris-setosa"]
print(df.tail())

    sl   sw   pl   pw  flower_type
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa
5  5.4  3.9  1.7  0.4  Iris-setosa
sl                     5.1
sw                     3.5
pl                     1.4
pw                     0.2
flower_type    Iris-setosa
Name: 0, dtype: object
sl                     5.4
sw                     3.9
pl                     1.7
pw                     0.4
flower_type    Iris-setosa
Name: 5, dtype: object
      sl   sw   pl   pw     flower_type
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  1.0  2.0  3.0  4.0     Iris-setosa
151  1.5  2.7  3.2  4.8     Iris-setosa

In [73]:

df.drop(df.index[1:10])

# now we would want to reset indices
print(df.reset_index())
print(df.head())
# pass drop = True to remove previous index column
print(df.reset_index(drop = True))
print(df.head())
# to make changes to the df itself pass inplace = True
print(df.reset_index(drop = True, inplace = True))
print(df.head())
# to remove column pass axis = 1
# inplace works here too

     index   sl   sw   pl   pw     flower_type  diff_sl_sw
0        0  5.1  3.5  1.4  0.2     Iris-setosa         1.6
1        1  4.9  3.0  1.4  0.2     Iris-setosa         1.9
2        2  4.7  3.2  1.3  0.2     Iris-setosa         1.5
3        3  4.6  3.1  1.5  0.2     Iris-setosa         1.5
4        4  5.0  3.6  1.4  0.2     Iris-setosa         1.4
5        5  5.4  3.9  1.7  0.4     Iris-setosa         1.5
6        6  4.6  3.4  1.4  0.3     Iris-setosa         1.2
7        7  5.0  3.4  1.5  0.2     Iris-setosa         1.6
8        8  4.4  2.9  1.4  0.2     Iris-setosa         1.5
9        9  4.9  3.1  1.5  0.1     Iris-setosa         1.8
10      10  5.4  3.7  1.5  0.2     Iris-setosa         1.7
11      11  4.8  3.4  1.6  0.2     Iris-setosa         1.4
12      12  4.8  3.0  1.4  0.1     Iris-setosa         1.8
13      13  4.3  3.0  1.1  0.1     Iris-setosa         1.3
14      14  5.8  4.0  1.2  0.2     Iris-setosa         1.8
15      15  5.7  4.4  1.5  0.4     Iris-setosa         1.3
16      16  5.4  3.9  1.3  0.4     Iris-setosa         1.5
17      17  5.1  3.5  1.4  0.3     Iris-setosa         1.6
18      18  5.7  3.8  1.7  0.3     Iris-setosa         1.9
19      19  5.1  3.8  1.5  0.3     Iris-setosa         1.3
20      20  5.4  3.4  1.7  0.2     Iris-setosa         2.0
21      21  5.1  3.7  1.5  0.4     Iris-setosa         1.4
22      22  4.6  3.6  1.0  0.2     Iris-setosa         1.0
23      23  5.1  3.3  1.7  0.5     Iris-setosa         1.8
24      24  4.8  3.4  1.9  0.2     Iris-setosa         1.4
25      25  5.0  3.0  1.6  0.2     Iris-setosa         2.0
26      26  5.0  3.4  1.6  0.4     Iris-setosa         1.6
27      27  5.2  3.5  1.5  0.2     Iris-setosa         1.7
28      28  5.2  3.4  1.4  0.2     Iris-setosa         1.8
29      29  4.7  3.2  1.6  0.2     Iris-setosa         1.5
..     ...  ...  ...  ...  ...             ...         ...
120    120  6.9  3.2  5.7  2.3  Iris-virginica         3.7
121    121  5.6  2.8  4.9  2.0  Iris-virginica         2.8
122    122  7.7  2.8  6.7  2.0  Iris-virginica         4.9
123    123  6.3  2.7  4.9  1.8  Iris-virginica         3.6
124    124  6.7  3.3  5.7  2.1  Iris-virginica         3.4
125    125  7.2  3.2  6.0  1.8  Iris-virginica         4.0
126    126  6.2  2.8  4.8  1.8  Iris-virginica         3.4
127    127  6.1  3.0  4.9  1.8  Iris-virginica         3.1
128    128  6.4  2.8  5.6  2.1  Iris-virginica         3.6
129    129  7.2  3.0  5.8  1.6  Iris-virginica         4.2
130    130  7.4  2.8  6.1  1.9  Iris-virginica         4.6
131    131  7.9  3.8  6.4  2.0  Iris-virginica         4.1
132    132  6.4  2.8  5.6  2.2  Iris-virginica         3.6
133    133  6.3  2.8  5.1  1.5  Iris-virginica         3.5
134    134  6.1  2.6  5.6  1.4  Iris-virginica         3.5
135    135  7.7  3.0  6.1  2.3  Iris-virginica         4.7
136    136  6.3  3.4  5.6  2.4  Iris-virginica         2.9
137    137  6.4  3.1  5.5  1.8  Iris-virginica         3.3
138    138  6.0  3.0  4.8  1.8  Iris-virginica         3.0
139    139  6.9  3.1  5.4  2.1  Iris-virginica         3.8
140    140  6.7  3.1  5.6  2.4  Iris-virginica         3.6
141    141  6.9  3.1  5.1  2.3  Iris-virginica         3.8
142    142  5.8  2.7  5.1  1.9  Iris-virginica         3.1
143    143  6.8  3.2  5.9  2.3  Iris-virginica         3.6
144    144  6.7  3.3  5.7  2.5  Iris-virginica         3.4
145    145  6.7  3.0  5.2  2.3  Iris-virginica         3.7
146    146  6.3  2.5  5.0  1.9  Iris-virginica         3.8
147    147  6.5  3.0  5.2  2.0  Iris-virginica         3.5
148    148  6.2  3.4  5.4  2.3  Iris-virginica         2.8
149    149  5.9  3.0  5.1  1.8  Iris-virginica         2.9

[150 rows x 7 columns]
    sl   sw   pl   pw  flower_type  diff_sl_sw
0  5.1  3.5  1.4  0.2  Iris-setosa         1.6
1  4.9  3.0  1.4  0.2  Iris-setosa         1.9
2  4.7  3.2  1.3  0.2  Iris-setosa         1.5
3  4.6  3.1  1.5  0.2  Iris-setosa         1.5
4  5.0  3.6  1.4  0.2  Iris-setosa         1.4
      sl   sw   pl   pw     flower_type  diff_sl_sw
0    5.1  3.5  1.4  0.2     Iris-setosa         1.6
1    4.9  3.0  1.4  0.2     Iris-setosa         1.9
2    4.7  3.2  1.3  0.2     Iris-setosa         1.5
3    4.6  3.1  1.5  0.2     Iris-setosa         1.5
4    5.0  3.6  1.4  0.2     Iris-setosa         1.4
5    5.4  3.9  1.7  0.4     Iris-setosa         1.5
6    4.6  3.4  1.4  0.3     Iris-setosa         1.2
7    5.0  3.4  1.5  0.2     Iris-setosa         1.6
8    4.4  2.9  1.4  0.2     Iris-setosa         1.5
9    4.9  3.1  1.5  0.1     Iris-setosa         1.8
10   5.4  3.7  1.5  0.2     Iris-setosa         1.7
11   4.8  3.4  1.6  0.2     Iris-setosa         1.4
12   4.8  3.0  1.4  0.1     Iris-setosa         1.8
13   4.3  3.0  1.1  0.1     Iris-setosa         1.3
14   5.8  4.0  1.2  0.2     Iris-setosa         1.8
15   5.7  4.4  1.5  0.4     Iris-setosa         1.3
16   5.4  3.9  1.3  0.4     Iris-setosa         1.5
17   5.1  3.5  1.4  0.3     Iris-setosa         1.6
18   5.7  3.8  1.7  0.3     Iris-setosa         1.9
19   5.1  3.8  1.5  0.3     Iris-setosa         1.3
20   5.4  3.4  1.7  0.2     Iris-setosa         2.0
21   5.1  3.7  1.5  0.4     Iris-setosa         1.4
22   4.6  3.6  1.0  0.2     Iris-setosa         1.0
23   5.1  3.3  1.7  0.5     Iris-setosa         1.8
24   4.8  3.4  1.9  0.2     Iris-setosa         1.4
25   5.0  3.0  1.6  0.2     Iris-setosa         2.0
26   5.0  3.4  1.6  0.4     Iris-setosa         1.6
27   5.2  3.5  1.5  0.2     Iris-setosa         1.7
28   5.2  3.4  1.4  0.2     Iris-setosa         1.8
29   4.7  3.2  1.6  0.2     Iris-setosa         1.5
..   ...  ...  ...  ...             ...         ...
120  6.9  3.2  5.7  2.3  Iris-virginica         3.7
121  5.6  2.8  4.9  2.0  Iris-virginica         2.8
122  7.7  2.8  6.7  2.0  Iris-virginica         4.9
123  6.3  2.7  4.9  1.8  Iris-virginica         3.6
124  6.7  3.3  5.7  2.1  Iris-virginica         3.4
125  7.2  3.2  6.0  1.8  Iris-virginica         4.0
126  6.2  2.8  4.8  1.8  Iris-virginica         3.4
127  6.1  3.0  4.9  1.8  Iris-virginica         3.1
128  6.4  2.8  5.6  2.1  Iris-virginica         3.6
129  7.2  3.0  5.8  1.6  Iris-virginica         4.2
130  7.4  2.8  6.1  1.9  Iris-virginica         4.6
131  7.9  3.8  6.4  2.0  Iris-virginica         4.1
132  6.4  2.8  5.6  2.2  Iris-virginica         3.6
133  6.3  2.8  5.1  1.5  Iris-virginica         3.5
134  6.1  2.6  5.6  1.4  Iris-virginica         3.5
135  7.7  3.0  6.1  2.3  Iris-virginica         4.7
136  6.3  3.4  5.6  2.4  Iris-virginica         2.9
137  6.4  3.1  5.5  1.8  Iris-virginica         3.3
138  6.0  3.0  4.8  1.8  Iris-virginica         3.0
139  6.9  3.1  5.4  2.1  Iris-virginica         3.8
140  6.7  3.1  5.6  2.4  Iris-virginica         3.6
141  6.9  3.1  5.1  2.3  Iris-virginica         3.8
142  5.8  2.7  5.1  1.9  Iris-virginica         3.1
143  6.8  3.2  5.9  2.3  Iris-virginica         3.6
144  6.7  3.3  5.7  2.5  Iris-virginica         3.4
145  6.7  3.0  5.2  2.3  Iris-virginica         3.7
146  6.3  2.5  5.0  1.9  Iris-virginica         3.8
147  6.5  3.0  5.2  2.0  Iris-virginica         3.5
148  6.2  3.4  5.4  2.3  Iris-virginica         2.8
149  5.9  3.0  5.1  1.8  Iris-virginica         2.9

[150 rows x 6 columns]
    sl   sw   pl   pw  flower_type  diff_sl_sw
0  5.1  3.5  1.4  0.2  Iris-setosa         1.6
1  4.9  3.0  1.4  0.2  Iris-setosa         1.9
2  4.7  3.2  1.3  0.2  Iris-setosa         1.5
3  4.6  3.1  1.5  0.2  Iris-setosa         1.5
4  5.0  3.6  1.4  0.2  Iris-setosa         1.4
None
    sl   sw   pl   pw  flower_type  diff_sl_sw
0  5.1  3.5  1.4  0.2  Iris-setosa         1.6
1  4.9  3.0  1.4  0.2  Iris-setosa         1.9
2  4.7  3.2  1.3  0.2  Iris-setosa         1.5
3  4.6  3.1  1.5  0.2  Iris-setosa         1.5
4  5.0  3.6  1.4  0.2  Iris-setosa         1.4

In [56]:
df.drop('sl', axis = 1)

      sw   pl   pw     flower_type
0    3.5  1.4  0.2     Iris-setosa
1    3.0  1.4  0.2     Iris-setosa
2    3.2  1.3  0.2     Iris-setosa
4    3.6  1.4  0.2     Iris-setosa
5    3.9  1.7  0.4     Iris-setosa
6    3.4  1.4  0.3     Iris-setosa
7    3.4  1.5  0.2     Iris-setosa
8    2.9  1.4  0.2     Iris-setosa
9    3.1  1.5  0.1     Iris-setosa
10   3.7  1.5  0.2     Iris-setosa
11   3.4  1.6  0.2     Iris-setosa
12   3.0  1.4  0.1     Iris-setosa
13   3.0  1.1  0.1     Iris-setosa
14   4.0  1.2  0.2     Iris-setosa
15   4.4  1.5  0.4     Iris-setosa
16   3.9  1.3  0.4     Iris-setosa
17   3.5  1.4  0.3     Iris-setosa
18   3.8  1.7  0.3     Iris-setosa
19   3.8  1.5  0.3     Iris-setosa
20   3.4  1.7  0.2     Iris-setosa
21   3.7  1.5  0.4     Iris-setosa
22   3.6  1.0  0.2     Iris-setosa
23   3.3  1.7  0.5     Iris-setosa
24   3.4  1.9  0.2     Iris-setosa
25   3.0  1.6  0.2     Iris-setosa
26   3.4  1.6  0.4     Iris-setosa
27   3.5  1.5  0.2     Iris-setosa
28   3.4  1.4  0.2     Iris-setosa
29   3.2  1.6  0.2     Iris-setosa
30   3.1  1.6  0.2     Iris-setosa
..   ...  ...  ...             ...
121  2.8  4.9  2.0  Iris-virginica
122  2.8  6.7  2.0  Iris-virginica
123  2.7  4.9  1.8  Iris-virginica
124  3.3  5.7  2.1  Iris-virginica
125  3.2  6.0  1.8  Iris-virginica
126  2.8  4.8  1.8  Iris-virginica
127  3.0  4.9  1.8  Iris-virginica
128  2.8  5.6  2.1  Iris-virginica
129  3.0  5.8  1.6  Iris-virginica
130  2.8  6.1  1.9  Iris-virginica
131  3.8  6.4  2.0  Iris-virginica
132  2.8  5.6  2.2  Iris-virginica
133  2.8  5.1  1.5  Iris-virginica
134  2.6  5.6  1.4  Iris-virginica
135  3.0  6.1  2.3  Iris-virginica
136  3.4  5.6  2.4  Iris-virginica
137  3.1  5.5  1.8  Iris-virginica
138  3.0  4.8  1.8  Iris-virginica
139  3.1  5.4  2.1  Iris-virginica
140  3.1  5.6  2.4  Iris-virginica
141  3.1  5.1  2.3  Iris-virginica
142  2.7  5.1  1.9  Iris-virginica
143  3.2  5.9  2.3  Iris-virginica
144  3.3  5.7  2.5  Iris-virginica
145  3.0  5.2  2.3  Iris-virginica
146  2.5  5.0  1.9  Iris-virginica
147  3.0  5.2  2.0  Iris-virginica
148  3.4  5.4  2.3  Iris-virginica
149  2.0  3.0  4.0     Iris-setosa
151  2.7  3.2  4.8     Iris-setosa

[150 rows x 4 columns]

In [68]:
df = iris.copy()
print(df.describe())
df.drop(0, axis = 1, inplace = True)
print(df.describe())
del df[1]
print(df.describe())

                0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667
std      0.828066    0.433594    1.764420    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000
                1           2           3
count  150.000000  150.000000  150.000000
mean     3.054000    3.758667    1.198667
std      0.433594    1.764420    0.763161
min      2.000000    1.000000    0.100000
25%      2.800000    1.600000    0.300000
50%      3.000000    4.350000    1.300000
75%      3.300000    5.100000    1.800000
max      4.400000    6.900000    2.500000
                2           3
count  150.000000  150.000000
mean     3.758667    1.198667
std      1.764420    0.763161
min      1.000000    0.100000
25%      1.600000    0.300000
50%      4.350000    1.300000
75%      5.100000    1.800000
max      6.900000    2.500000

In [71]:
df = iris.copy()
df.describe()

               sl          sw          pl          pw
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667
std      0.828066    0.433594    1.764420    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [72]:
# add a column
df['diff_sl_sw'] = df['sl'] - df['sw']
df.describe()

               sl          sw          pl          pw  diff_sl_sw
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667    2.789333
std      0.828066    0.433594    1.764420    0.763161    0.975825
min      4.300000    2.000000    1.000000    0.100000    1.000000
25%      5.100000    2.800000    1.600000    0.300000    1.800000
50%      5.800000    3.000000    4.350000    1.300000    3.000000
75%      6.400000    3.300000    5.100000    1.800000    3.600000
max      7.900000    4.400000    6.900000    2.500000    5.100000